name: Main

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      working-directory: ./app
      run: composer validate --strict

    - name: Install dependencies
      working-directory: ./app
      run: composer install --prefer-dist --no-progress

    - name: Run PSALM
      working-directory: ./app
      run: ./vendor/bin/psalm

